# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e514ef18fb61046c6d383bc0e458bb947a4a59074f919e1b700ced2662de3b324104795338312ca3e365421d4c6992808028be40771d3d27576e46f248aee16b

test:
  secret_key_base: 896cfb1974ba428d581c1115fabe2e138494c17993080dba5f52346f439bac26332efa68c4c163ab82bbec67f86612af9920e2d4f89a38c557addce1e31ce754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
